# try-except

In [1]:
import pandas as pd

In [2]:
def importa_clima(file_path):
    """Importa un archivo CSV y pone la columna 0 como índice, regresa un dataframe vacio si la ruta es incorrecta"""
    try:
        df = pd.read_csv(file_path,index_col=0,parse_dates=True)    
    except:
        print("El archivo o ruta es incorrecto")
        print(file_path)
        df = None
    finally:
        return df

In [3]:
importa_clima("../../data/Temixco_2018_10Min.csv")

                        Ib   Ig     To     RH     WS     WD         P
time
2018-01-01 00:00:00    NaN  NaN  18.70  36.34  1.422  316.0  87864.11
2018-01-01 00:10:00  0.002  0.0  18.95  35.29  1.008  283.7  87876.37
2018-01-01 00:20:00  0.170  0.0  18.94  35.43  1.565  326.0  87888.64
2018-01-01 00:30:00  0.371  0.0  18.77  35.89  2.175  354.5  87887.21
2018-01-01 00:40:00  0.305  0.0  18.81  36.34  1.902  348.0  87886.91
...                    ...  ...    ...    ...    ...    ...       ...
2018-12-31 23:10:00  0.125  0.0  18.51  47.29  1.715  332.2  87484.32
2018-12-31 23:20:00  0.000  0.0  18.26  48.02  1.703  320.5  87470.70
2018-12-31 23:30:00  0.044  0.0  18.39  46.84  2.887  335.7  87455.03
2018-12-31 23:40:00  0.170  0.0  17.99  47.85  1.528  358.8  87470.02
2018-12-31 23:50:00  0.003  0.0  17.75  49.65  0.598  322.3  87467.29

[52560 rows x 7 columns]

In [4]:
a = importa_clima("../../data/Temixco_2018_10Min_.csv")

El archivo o ruta es incorrecto
../../data/Temixco_2018_10Min_.csv

In [5]:
a